### ISSUE TITLE
runtime error 搜索各站点时出现运行时错误

### ISSUE THREAD

**Issue by cxumol** [ma6254/FictionDown#27]
```
R:\down\FictionDown_0.1.3_Windows_x86_64.tar>FictionDown s -k '赛博剑仙铁雨'
2021/09/04 00:37:18 搜索站点: 新八一中文网 https://www.81new.net/ 404 404 Not Found
2021/09/04 00:37:19 搜索站点: 结果: 0 笔趣阁1 https://www.biquge5200.cc/
2021/09/04 00:37:20 搜索站点: 结果: 0 起点中文网 https://www.qidian.com/
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x9acbec]

goroutine 1 [running]:
github.com/ma6254/FictionDown/site.Type1SearchAfter.func1(0xc00002c340, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/runner/work/FictionDown/FictionDown/site/sites.go:200 +0x24c
github.com/ma6254/FictionDown/site.Search(0xc00002c340, 0x14, 0xc00013d9e0, 0xc00002c340, 0x14, 0xc0000897a0, 0x4efadf)
        /home/runner/work/FictionDown/FictionDown/site/site.go:238 +0x13c
main.glob..func6(0xc000092f20, 0x0, 0xc000092f20)
        /home/runner/work/FictionDown/FictionDown/search.go:33 +0x7f
github.com/urfave/cli.HandleAction(0xa2c980, 0xb279f0, 0xc000092f20, 0xc00013d900, 0x0)
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xcf
github.com/urfave/cli.Command.Run(0xaf472e, 0x6, 0x0, 0x0, 0x1118610, 0x1, 0x1, 0xb00290, 0x12, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x99d
github.com/urfave/cli.(*App).Run(0x1121fc0, 0xc000054100, 0x4, 0x4, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x6b6
main.main()
        /home/runner/work/FictionDown/FictionDown/main.go:87 +0x125
```

运行环境: windows x64, linux x64  
网络环境: 海外IP

稳定复现

**Comment by ma6254** [comment]
试试clone下来安装
这个软件我很久没维护了，一堆问题
```
git clone https://github.com/ma6254/FictionDown.git
cd FictionDown
go install .
```

**Comment by asdfasdf2424110** [comment]
为什么刚打开就会闪退？
